/*
 * generated by Xtext
 */
package lu.ses.engineering.spell.refactoring.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import lu.ses.engineering.spell.refactoring.services.RefactoringDefinitionGrammarAccess;

public class RefactoringDefinitionParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private RefactoringDefinitionGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens();
	}
	
	@Override
	protected lu.ses.engineering.spell.refactoring.parser.antlr.internal.InternalRefactoringDefinitionParser createParser(XtextTokenStream stream) {
		return new lu.ses.engineering.spell.refactoring.parser.antlr.internal.InternalRefactoringDefinitionParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Refactorings";
	}
	
	public RefactoringDefinitionGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(RefactoringDefinitionGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
