/**
 *
 * $Id$
 */
package com.astra.ses.spell.dev.database.webapi.dbModel.validation;

import com.astra.ses.spell.dev.database.interfaces.ITelecommand;

/**
 * A sample validator interface for {@link java.util.Map.Entry}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface StringToTCMapEntryValidator {
	boolean validate();

	boolean validateTypedKey(String value);
	boolean validateTypedValue(ITelecommand value);
}
