/**
 *
 * $Id$
 */
package com.astra.ses.spell.dev.database.webapi.dbModel.validation;

import com.astra.ses.spell.dev.database.interfaces.ArgumentType;
import com.astra.ses.spell.dev.database.interfaces.ICalibration;
import com.astra.ses.spell.dev.database.interfaces.ISpellDatabase;
import com.astra.ses.spell.dev.database.interfaces.Radix;


/**
 * A sample validator interface for {@link com.astra.ses.spell.dev.database.impl.TelecommandArgument}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface WebAPITelecommandArgumentValidator {
	boolean validate();

	boolean validateDescription(String value);

	boolean validateName(String value);

	boolean validateLoaded(boolean value);

	boolean validateType(ArgumentType value);

	boolean validateRadix(Radix value);

	boolean validateUnits(String value);

	boolean validateDefaultValue(String value);

	boolean validateCalibrated(boolean value);

	boolean validateOptional(boolean value);

	boolean validateCalibrationId(String value);

	boolean validateDatabase(ISpellDatabase value);

	boolean validateCalibration(ICalibration value);
}
