/**
 *
 * $Id$
 */
package com.astra.ses.spell.dev.database.webapi.dbModel.validation;

import com.astra.ses.spell.dev.database.interfaces.ICalibration;
import com.astra.ses.spell.dev.database.interfaces.ITelecommand;
import com.astra.ses.spell.dev.database.interfaces.ITelemetryDisplayDefinition;
import com.astra.ses.spell.dev.database.interfaces.ITelemetryParameter;

import com.astra.ses.spell.dev.database.webapi.DatabaseConnection;

import java.util.Collection;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.common.util.EMap;

/**
 * A sample validator interface for {@link com.astra.ses.spell.dev.database.interfaces.ISpellDatabase}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface WebAPIDatabaseValidator {
	boolean validate();

	boolean validateDatabasePath(String value);
	boolean validateName(String value);
	boolean validateVersion(String value);
	boolean validateTelemetryParameterNames(Collection<String> value);
	boolean validateTelecommandNames(Collection<String> value);
	boolean validateCalibrationNames(Collection<String> value);
	boolean validateDisplays(EList<ITelemetryDisplayDefinition> value);
	boolean validateTmModels(EMap<String, ITelemetryParameter> value);
	boolean validateLastTMUpdateHash(String value);
	boolean validateLastTCUpdateHash(String value);
	boolean validateTcModels(EMap<String, ITelecommand> value);
	boolean validateCalibrationModels(EMap<String, ICalibration> value);
	boolean validateDbConnection(DatabaseConnection value);
}
