/**
 *
 * $Id$
 */
package com.astra.ses.spell.dev.database.webapi.dbModel.validation;

import com.astra.ses.spell.dev.database.interfaces.CalibrationType;

import com.astra.ses.spell.dev.database.interfaces.ISpellDatabase;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.common.util.EMap;

/**
 * A sample validator interface for {@link com.astra.ses.spell.dev.database.interfaces.ICalibration}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface WebAPICalibrationModelValidator {
	boolean validate();

	boolean validateType(CalibrationType value);
	boolean validateIdentifier(String value);
	boolean validateCachedWebAPIData(String value);
	boolean validateValidValues(EList<String> value);
	boolean validateInternalValidValues(EMap<String, String> value);

	boolean validateDatabase(ISpellDatabase value);
}
