/**
 *
 * $Id$
 */
package com.astra.ses.spell.dev.database.webapi.dbModel.validation;

import com.astra.ses.spell.dev.database.interfaces.ICalibration;
import com.astra.ses.spell.dev.database.interfaces.IMonitoringCheck;
import com.astra.ses.spell.dev.database.interfaces.ISpellDatabase;

import java.util.Collection;

/**
 * A sample validator interface for {@link com.astra.ses.spell.dev.database.interfaces.ITelemetryParameter}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface WebAPITelemetryModelValidator {
	boolean validate();

	boolean validateLastUpdateHash(int value);
	boolean validateMeasuringUnit(String value);
	boolean validateCalibrations(Collection<String> value);
	boolean validateCalibration(ICalibration value);
	boolean validateDefaultCalibrationId(String value);
	boolean validateMonitoringChecks(Collection<? extends IMonitoringCheck> value);
	boolean validateDatabase(ISpellDatabase value);
	boolean validateLoaded(boolean value);
}
