/**
 *
 * $Id$
 */
package com.astra.ses.spell.dev.database.webapi.dbModel.validation;

import com.astra.ses.spell.dev.database.impl.TelecommandArgument;

import com.astra.ses.spell.dev.database.interfaces.ISpellDatabase;
import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.astra.ses.spell.dev.database.interfaces.ITelecommand}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface WebAPITelecommandModelValidator {
	boolean validate();

	boolean validateCritical(boolean value);
	boolean validateArguments(EList<TelecommandArgument> value);
	boolean validateDatabase(ISpellDatabase value);
	boolean validateLoaded(boolean value);
}
