/*
 * generated by Xtext
 */
package lu.ses.engineering.spell.refactoring;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class RefactoringDefinitionUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return lu.ses.engineering.spell.refactoring.ui.internal.RefactoringDefinitionActivator.getInstance().getInjector("lu.ses.engineering.spell.refactoring.RefactoringDefinition");
	}
	
}
