/*
* generated by Xtext
*/
package lu.ses.engineering.spell;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class SpellDatabaseStandaloneSetup extends SpellDatabaseStandaloneSetupGenerated{

	public static void doSetup() {
		new SpellDatabaseStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

