/*
 * generated by Xtext
 */
package lu.ses.engineering.B7022SPELL.WorkspaceGrammar;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ReportGrammarRuntimeModule extends lu.ses.engineering.B7022SPELL.WorkspaceGrammar.AbstractReportGrammarRuntimeModule {

}
