/*
* generated by Xtext
*/
package lu.ses.engineering.B7022SPELL.WorkspaceGrammar;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ReportGrammarStandaloneSetup extends ReportGrammarStandaloneSetupGenerated{

	public static void doSetup() {
		new ReportGrammarStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

