/*
* generated by Xtext
*/
package lu.ses.engineering.B7022SPELL.pages;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class TmDisplayPagesStandaloneSetup extends TmDisplayPagesStandaloneSetupGenerated{

	public static void doSetup() {
		new TmDisplayPagesStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

