/*
 * generated by Xtext
 */
package lu.ses.engineering.B7022SPELL.pages;

import org.eclipse.xtext.conversion.IValueConverterService;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TmDisplayPagesRuntimeModule extends lu.ses.engineering.B7022SPELL.pages.AbstractTmDisplayPagesRuntimeModule {

}
