/*
 * generated by Xtext
 */
package lu.ses.engineering.spell.controlflow.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SpellGrammarUiModule extends lu.ses.engineering.spell.controlflow.ui.AbstractSpellGrammarUiModule {
	public SpellGrammarUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
