/*
 * generated by Xtext
 */
package lu.ses.engineering.spell.refactoring.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import lu.ses.engineering.spell.refactoring.ui.internal.RefactoringDefinitionActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RefactoringDefinitionExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return RefactoringDefinitionActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return RefactoringDefinitionActivator.getInstance().getInjector(RefactoringDefinitionActivator.LU_SES_ENGINEERING_SPELL_REFACTORING_REFACTORINGDEFINITION);
	}
	
}
