/*
 * generated by Xtext
 */
package lu.ses.engineering.spell.ui.contentassist

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class SpellDatabaseProposalProvider extends AbstractSpellDatabaseProposalProvider {
   
    
}
