/*
* generated by Xtext
*/
package lu.ses.engineering.B7022SPELL.pages.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class TmDisplayPagesAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("lu/ses/engineering/B7022SPELL/pages/parser/antlr/internal/InternalTmDisplayPages.tokens");
	}
}
