/*
* generated by Xtext
*/
package lu.ses.engineering.B7022SPELL.pages.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import lu.ses.engineering.B7022SPELL.pages.services.TmDisplayPagesGrammarAccess;

public class TmDisplayPagesParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private TmDisplayPagesGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS");
	}
	
	@Override
	protected lu.ses.engineering.B7022SPELL.pages.parser.antlr.internal.InternalTmDisplayPagesParser createParser(XtextTokenStream stream) {
		return new lu.ses.engineering.B7022SPELL.pages.parser.antlr.internal.InternalTmDisplayPagesParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "TmDisplayPage";
	}
	
	public TmDisplayPagesGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(TmDisplayPagesGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
