/*
 * generated by Xtext
 */
package lu.ses.engineering.spell.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractSpellDatabaseValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(lu.ses.engineering.spell.spellDatabase.SpellDatabasePackage.eINSTANCE);
		return result;
	}
}
