/*
 * generated by Xtext
 */
package lu.ses.engineering.spell.refactoring.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class RefactoringDefinitionUiModule extends lu.ses.engineering.spell.refactoring.ui.AbstractRefactoringDefinitionUiModule {
	public RefactoringDefinitionUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
