/*
 * generated by Xtext
 */
package lu.ses.engineering.spell.controlflow.ui.contentassist

import lu.ses.engineering.spell.controlflow.ui.contentassist.AbstractSpellGrammarProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class SpellGrammarProposalProvider extends AbstractSpellGrammarProposalProvider {
}
