/*
* generated by Xtext
*/
package lu.ses.engineering.spell.refactoring;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class RefactoringDefinitionStandaloneSetup extends RefactoringDefinitionStandaloneSetupGenerated{

	public static void doSetup() {
		new RefactoringDefinitionStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

