/*
 * generated by Xtext
 */
package lu.ses.engineering.spell.refactoring;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RefactoringDefinitionRuntimeModule extends lu.ses.engineering.spell.refactoring.AbstractRefactoringDefinitionRuntimeModule {

}
