/*
 * generated by Xtext
 */
package lu.ses.engineering.spell.controlflow;

import org.eclipse.xtext.conversion.IValueConverterService;
import org.eclipse.xtext.parsetree.reconstr.impl.DefaultCommentAssociater;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SpellGrammarRuntimeModule extends AbstractSpellGrammarRuntimeModule {
	
	public Class<? extends DefaultCommentAssociater> bindCommentAssociater()
    {
            return SpellCommentAssociater.class;
    }
	@Override
	public Class<? extends IValueConverterService> bindIValueConverterService() {
		return SPELLValueConverterService.class;
	}
	
}
