/*
* generated by Xtext
*/
package lu.ses.engineering.spell.controlflow;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class SpellGrammarStandaloneSetup extends SpellGrammarStandaloneSetupGenerated{

	public static void doSetup() {
		new SpellGrammarStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

