/*
* generated by Xtext
*/
package lu.ses.engineering.B7022SPELL.WorkspaceGrammar.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ReportGrammarAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("lu/ses/engineering/B7022SPELL/WorkspaceGrammar/parser/antlr/internal/InternalReportGrammar.tokens");
	}
}
