/*
* generated by Xtext
*/
package lu.ses.engineering.B7022SPELL.WorkspaceGrammar.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import lu.ses.engineering.B7022SPELL.WorkspaceGrammar.services.ReportGrammarGrammarAccess;

public class ReportGrammarParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private ReportGrammarGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens();
	}
	
	@Override
	protected lu.ses.engineering.B7022SPELL.WorkspaceGrammar.parser.antlr.internal.InternalReportGrammarParser createParser(XtextTokenStream stream) {
		return new lu.ses.engineering.B7022SPELL.WorkspaceGrammar.parser.antlr.internal.InternalReportGrammarParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Workspace";
	}
	
	public ReportGrammarGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ReportGrammarGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
