/*
 * generated by Xtext
 */
package lu.ses.engineering.spell.controlflow.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SpellGrammarAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("lu/ses/engineering/spell/controlflow/parser/antlr/internal/InternalSpellGrammar.tokens");
	}
}
