/*
 * generated by Xtext
 */
package lu.ses.engineering.spell.refactoring.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractRefactoringDefinitionValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(lu.ses.engineering.spell.refactoring.refactoringDefinition.RefactoringDefinitionPackage.eINSTANCE);
		return result;
	}
}
