/*
 * generated by Xtext
 */
package lu.ses.engineering.spell.refactoring.ui.contentassist

import lu.ses.engineering.spell.refactoring.ui.contentassist.AbstractRefactoringDefinitionProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class RefactoringDefinitionProposalProvider extends AbstractRefactoringDefinitionProposalProvider {
}
