/*
 * generated by Xtext
 */
package lu.ses.engineering.spell.controlflow.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractSpellGrammarValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://lu.ses.engineering.controlflow.grammar"));
		return result;
	}
}
